name: Print context and events
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  print:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 17.x ]
    steps:
      - name: Print workflow msg
        run: echo Print github object
      - name: Print git obj
        run: echo "${{ toJSON(github.event) }}"